//
//  NewsDataSource.swift
//  WSP.KBTU
//
//  Created by Lidiya Karnaukhova on 26.04.2022.
//

import Foundation

class NewsDataSource {
    let news: [NewsCellConfigurator] = [
        NewsCellConfigurator(item: News(newsTitle: "UAE announces 373 new COVID-19 cases, 347 recoveries, no deaths in last 24 hours", newsDescription: "The Ministry of Health and Prevention (MoHAP) announced that it conducted 238,458 additional COVID-19 tests over the past 24 hours, using state-of-the-art medical testing equipment, WAM reports. In a statement on Wednesday, the Ministry stressed its aim to continue expanding the scope of testing nationwide to facilitate the early detection of coronavirus cases and carry out the necessary treatment. As part of its intensified testing campaign, MoHAP announced 373 new coronavirus cases, bringing the total number of recorded cases in the UAE to 905,841. According to the Ministry, the infected individuals are from various nationalities, are in a stable condition, and receiving the necessary care. The Ministry added that no COVID-19-related deaths have been recorded in the past 24 hours, leaving the death toll unchanged at 2,302. MoHAP also noted that an additional 347 individuals had fully recovered from COVID-19, bringing the total number of recoveries to 889,609.", newsDate: "MAY 25, 2022  19:14")),
        NewsCellConfigurator(item: News(newsTitle: "S. Korea sets June 15 as 2nd launch date of homegrown space rocket", newsDescription: "South Korea on Wednesday set June 15 as the second launch date of its homegrown space rocket Nuri, eight months after the first launch failed to put a dummy satellite into orbit, Yonhap reports. Nuri, also known as KSLV-II, is set to lift off from the Naro Space Center in the country's southern coastal village of Goheung between 3 p.m. and 5 p.m, though the exact time will be determined on that day, the Ministry of Science and ICT said. The ministry set the period between June 16 and June 23 as the launch window after holding a meeting of its launch management committee with the state-run Korea Aerospace Research Institute in Goheung. In October, Nuri successfully flew to a target altitude of 700 kilometers but failed to put a dummy satellite into orbit as its third-stage engine burned out earlier than expected. South Korea announced in February it will make a second attempt to launch Nuri in mid-June and had tentatively set June 15 as the launch date.", newsDate: "MAY 25, 2022  18:39")),
        NewsCellConfigurator(item: News(newsTitle: "President Tokayev condoles over deadly shooting at Texas elementary school", newsDescription: "President Kassym-Jomart Tokayev sent a telegram of condolences to President of the United States of America Joseph Biden in connection with the shooting at the Robb Elementary School in Uvalde, Texas, that took the lives of innocent children and adults, Kazinform cites the Akorda press service. «On behalf of the people of Kazakhstan and on my own behalf, I express the most sincere condolences and sympathy to the bereaved families who lost their beloved ones, and wish a speedy recovery to those wounded. I join Texans and all your country-fellows in grieving for the victims of this heinous crime,» President Tokayev writes in his letter.", newsDate: "MAY 25, 2022  16:55")),
        NewsCellConfigurator(item: News(newsTitle: "10 regions of Kazakhstan put on storm alert", newsDescription: "Storm alert was issued for 10 regions of Kazakhstan, Kazinform cites the National Met Office Kazhydromet. The north and west of Akmola region are to expect easterly, southeasterly wind at 15-20 mps during the day on May 25. The east of Aktobe region is to brace for thunderstorms. Southeasterly wind turning northwestward is predicted to reach 15-18 amps at daytime in the east. Atyrau region is to see thunderstorms in the east at night on May 25. Northwesterly wind is to gust up to 15-20 mps in the east. High fire hazard is to persist in East Kazakhstan region's Zharminsky district as well as the city of Semey.", newsDate: "MAY 24, 2022 20:20")),
        NewsCellConfigurator(item: News(newsTitle: "Turkestan and Kyzylorda regions reduce rice planting areas", newsDescription: "The situation with water management is stable in the southern regions of Kazakhstan, Minister of Ecology, Geology, and Natural Resources of Kazakhstan Serikkali Brekeshyev said, Kazinform correspondent reports.Reconstruction of 259 hydrotechnical installations in the basins of transboundary rivers is carried out in Kazakhstan. According to the Ecology Ministry, mechanical cleaning of 535km of main and interfirm channels as well as the purchase and installation of 67 pumping installations is carried out. The said works are to be completed by the end of June this year.", newsDate: "MAY 24, 2022 19:14")),
        NewsCellConfigurator(item: News(newsTitle: "67 monkeypox cases found in nine EU countries over last week", newsDescription: "Nine member-states of the European Union (Austria, Belgium, France, Germany, Italy, the Netherlands, Portugal, Spain and Sweden) registered 67 monkeypox cases in total from May 15 to 23, the European Center for Disease Prevention and Control (ECDC) said in its press release, TASS reports. «Human-to-human transmission occurs through close contact with infectious material from skin lesions of an infected person, through respiratory droplets in prolonged face-to-face contact, and through fomites,» the Center said. The predominance in the current outbreak of diagnosed human monkeypox cases among men having sex with men and the nature of the presenting lesions in some cases suggest transmission occurred during sexual intercourse, ECDC said.", newsDate: "MAY 24, 2022 16:46")),
        NewsCellConfigurator(item: News(newsTitle: "Population of Kyrgyzstan makes 6.7 mln people", newsDescription: "As of January 1, 2022, the permanent population of the republic amounted to 6.7 million people, according to a brief statistical guide of the National Statistical Committee «Kyrgyzstan,» Kabar reports. According to data of the magazine, on average 34 people are per 1 square kilometer in the republic. The population of the capital city of Bishkek at the beginning of 2022 was 1.1 million people.", newsDate: "MAY 23, 2022 21:14")),
        NewsCellConfigurator(item: News(newsTitle: "Over 800,000 teens immunized with Pfizer vaccine in Kazakhstan", newsDescription: "Over 39,000 pregnant women were inoculated with the first dose of Pfizer vaccine as of May 21, Kazinform has learned from the Telegram channel of the Inter-departmental commission fighting to prevent the spread of COVID-19. 1,135,688 people got vaccinated with the first dose of Pfizer vaccine, including 844,693 teenagers, 140,004 nursing mothers and 39,330 pregnant women.", newsDate: "MAY 22, 2022 14:38"))
    ]
    
    func getNewsData() -> [NewsCellConfigurator] {
        return news
    }
}
